repos:
  - repo: local
    hooks:
      - id: pnpm-fmt
        name: Format code with pnpm fmt
        entry: pnpm
        args: ['fmt']
        language: system
        pass_filenames: false
        always_run: true
