name: Build Examples

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nextjs-checks:
    runs-on: ubuntu-latest
    env:
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      IRON_SESSION_SECRET_KEY: ${{ secrets.IRON_SESSION_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint example
        run: |
          cd examples/elevenlabs-nextjs
          pnpm run lint

      - name: Build example
        run: |
          cd examples/elevenlabs-nextjs
          pnpm run build
