name: Check Documentation Links

on:
  pull_request:
    paths:
      - 'fern/**'
      - '.github/workflows/check-links.yml'

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Fern
        run: npm install -g fern-api

      - name: Create link checker script
        run: |
          cat > check_docs_links.sh << 'EOF'
          #!/bin/bash

          # Run broken-links command and capture output
          output=$(fern docs broken-links)

          # Filter only lines with broken links inside /docs/ or external docs
          echo "$output" | grep -E 'broken link to /(docs|elevenlabs\.io/docs)' > filtered_output.txt

          # Check if there are still relevant broken links
          if [[ -s filtered_output.txt ]]; then
            echo "Detected broken links in /docs or allowed external docs:"
            cat filtered_output.txt
            exit 1
          else
            echo "No relevant broken links found."
            exit 0
          fi
          EOF
          chmod +x check_docs_links.sh

      - name: Check documentation links
        run: ./check_docs_links.sh
