name: fern-check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Fern
        run: npm install -g fern-api

      - name: Check Fern API is valid
        run: fern check
