name: Format docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - name: Format docs
        run: pnpm run format:check
