name: Create Typescript SDK branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the Typescript SDK that you would like to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Release TypeScript SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          fern generate --group typescript-sdk --version ${{ inputs.version }} --log-level debug --api api
