name: Validate Formatting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - name: Validate formatting
        run: pnpm run fmt:check
