name: Validate docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Validate
        run: pnpm dlx fern-api check
